version: '3.4'
services:

  micro-services-viber:
    build: ./
    container_name: micro-services-viber
    image: micseres/micro-services-viber
    networks:
      erp:
        ipv4_address: 10.7.0.102
      go:
        ipv4_address: 10.9.0.102
    volumes:
      - ./:/app
    restart: always

networks:
  go:
    external: true
  erp:
    external: true
#docker network create --gateway 10.9.0.1 --subnet 10.9.0.0/24 go